[package]
name = "asus-notify"
version = "2.0.4"
authors = ["Luke D Jones <luke@ljones.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# serialisation
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
asus-nb = { path = "../asus-nb" }
asus-nb-ctrl = { path = "../asus-nb-ctrl" }
zbus = "^1.8"
zvariant = "^2.4"

[dependencies.notify-rust]
version = "^4.0"
default-features = false
features = ["z"]