
include:
  - remote: 'https://jobs.r2devops.io/latest/cargo_clippy.yml'
  - remote: 'https://jobs.r2devops.io/latest/cargo_build.yml'

stages:
  - static_tests
  - build

variables:
  GIT_SUBMODULE_STRATEGY: normal

before_script:
  - apt-get update -qq && apt-get install -y -qq libdbus-1-dev libclang-dev libudev-dev

cargo_build:
  only:
    - main

  variables:
    OUTPUT_DIR: "cargo-config"

  artifacts:
    when: always
    paths:
      - $PROJECT_ROOT/$OUTPUT_DIR
