
include:
  #  Remove the scope berfore Merging
  - remote: 'https://jobs.r2devops.io/latest/cargo_clippy.yml?scope=0.yml'
  - remote: 'https://jobs.r2devops.io/latest/cargo_build.yml?scope=0.yml'
  - remote: 'https://jobs.r2devops.io/latest/cargo_doc.yml?scope=0.yml'
  - remote: 'https://jobs.r2devops.io/pages.yml?scope=0.yml'

stages:
  - static_tests
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: normal

before_script:
  - apt-get update -qq && apt-get install -y -qq libdbus-1-dev libclang-dev libudev-dev
