[package]
name = "rog_platform"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "*"
udev = "^0.6"
rusb = "^0.9"
sysfs-class = "^0.1"